Repository status-im/status-go, pull requests merged in 2019-07, with the labels that each got.

#1528 Update mailserver docker readme.
  _assets/compose/mailserver/README.md
Labels: docs

#1500 add multi-account support
  .codeclimate.yml
  account/accounts.go
  account/generator/account.go
  account/generator/generator.go
  account/generator/generator_test.go
  account/generator/path_decoder.go
  account/generator/path_decoder_test.go
  account/generator/utils.go
  account/generator/utils_test.go
  account/onboarding.go
  account/onboarding_test.go
  account/utils.go
  account/utils_test.go
  api/backend.go
  extkeys/hdkey.go
  go.mod
  go.sum
  lib/library_test_multiaccount.go
  lib/library_test_utils.go
  lib/multiaccount.go
  mobile/multiaccount.go
  node/node.go
  t/e2e/accounts/accounts_test.go
  vendor/github.com/ethereum/go-ethereum/accounts/keystore/key.go
  vendor/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go
  vendor/github.com/ethereum/go-ethereum/p2p/dial.go
  vendor/github.com/ethereum/go-ethereum/p2p/server.go
  vendor/modules.txt
Labels: security

#1542 add multi-account LoadAccount, ImportMnemonic, and Reset functions
  account/generator/README.md
  lib/library_test_multiaccount.go
  lib/library_test_utils.go
  lib/multiaccount.go
  mobile/multiaccount.go
Labels: security

#1525 Multi account login
  account/accounts.go
  account/accounts_test.go
  account/utils.go
  api/backend.go
  api/backend_subs_test.go
  api/backend_test.go
  lib/library.go
  lib/library_test_utils.go
  mobile/status.go
  services/status/account_mock.go
  services/status/api.go
  services/status/api_test.go
  services/status/service.go
  t/devtests/tranfers_test.go
  t/e2e/accounts/accounts_rpc_test.go
  t/e2e/accounts/accounts_test.go
  t/e2e/transactions/transactions_test.go
  t/e2e/whisper/whisper_test.go
Labels: security

#1550 Fix release builds
  Makefile
  _assets/ci/Jenkinsfile
  _assets/ci/Jenkinsfile.android
  _assets/ci/Jenkinsfile.docker
  _assets/ci/Jenkinsfile.ios
  _assets/ci/Jenkinsfile.linux
  _assets/ci/Jenkinsfile.xgo
Labels: jenkins
