Repository status-im/status-go, pull requests merged in 2020-02, with the labels that each got.

#1825 [status-im/status-react#9942] relative paths
  VERSION
  api/geth_backend.go
  api/nimbus_backend.go
  lib/library_test_utils.go
  node/get_status_node.go
  node/geth_status_node_test.go
  node/nimbus_status_node.go
  params/config.go
  t/e2e/suites.go
Labels: blocker, v1 release

#1811 include mail password when getting enode with get_enode.sh
  _assets/compose/mailserver/Makefile
  _assets/compose/mailserver/README.md
  _assets/scripts/get_enode.sh
  _assets/systemd/mailserver/Makefile
  _assets/systemd/mailserver/README.md
Labels: devops

#1831 docs: clarify purpose and describe ports
  BOOTNODE.md
  MAILSERVER.md
  _assets/compose/bootnode/Makefile
  _assets/compose/bootnode/README.md
  _assets/systemd/bootnode/Makefile
  _assets/systemd/bootnode/README.md
Labels: docs

#1847 rename gomarkdown/markdown to status-im/markdown
  Makefile
  api/nimbus_backend.go
  go.mod
  go.sum
  mailserver/mailserver_db_postgres_test.go
  protocol/message.go
  services/ext/node_mock.go
  vendor/github.com/status-im/markdown/.gitignore
  vendor/github.com/status-im/markdown/.gitpod
  vendor/github.com/status-im/markdown/.travis.yml
  vendor/github.com/status-im/markdown/LICENSE.txt
  vendor/github.com/status-im/markdown/README.md
  vendor/github.com/status-im/markdown/ast/attribute.go
  vendor/github.com/status-im/markdown/ast/doc.go
  vendor/github.com/status-im/markdown/ast/node.go
  vendor/github.com/status-im/markdown/ast/print.go
  vendor/github.com/status-im/markdown/changes-from-blackfriday.md
  vendor/github.com/status-im/markdown/codecov.yml
  vendor/github.com/status-im/markdown/doc.go
  vendor/github.com/status-im/markdown/fuzz.go
  vendor/github.com/status-im/markdown/go.mod
  vendor/github.com/status-im/markdown/go.sum
  vendor/github.com/status-im/markdown/markdown.go
  vendor/github.com/status-im/markdown/parser/aside.go
  vendor/github.com/status-im/markdown/parser/attribute.go
  vendor/github.com/status-im/markdown/parser/block.go
  vendor/github.com/status-im/markdown/parser/callout.go
  vendor/github.com/status-im/markdown/parser/caption.go
  vendor/github.com/status-im/markdown/parser/citation.go
  vendor/github.com/status-im/markdown/parser/esc.go
  vendor/github.com/status-im/markdown/parser/figures.go
  vendor/github.com/status-im/markdown/parser/include.go
  vendor/github.com/status-im/markdown/parser/inline.go
  vendor/github.com/status-im/markdown/parser/matter.go
  vendor/github.com/status-im/markdown/parser/options.go
  vendor/github.com/status-im/markdown/parser/parser.go
  vendor/github.com/status-im/markdown/parser/ref.go
  vendor/github.com/status-im/markdown/todo.md
  vendor/github.com/status-im/markdown/tracking-perf.md
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_fileno.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_ino.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_namlen_bsd.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_namlen_linux.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_unix.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/semver/semver.go
  vendor/modules.txt
Labels: dependency
