Repository status-im/status-go, pull requests merged in 2020-04, with the labels that each got.

#1932 expose the mailserver metrics port by default
  MAILSERVER.md
  _assets/compose/mailserver/Makefile
  _assets/compose/mailserver/README.md
  _assets/compose/mailserver/docker-compose.yml
  _assets/scripts/gen_config.sh
  _assets/systemd/mailserver/Makefile
  _assets/systemd/mailserver/README.md
  _assets/systemd/mailserver/service.template
Labels: devops, docs

#1930 set archived_envelopes_total on start based on DB count
  mailserver/cleaner_test.go
  mailserver/mailserver_db.go
  mailserver/mailserver_db_leveldb.go
  mailserver/mailserver_db_postgres.go
  mailserver/metrics.go
Labels: metrics

#1946 Update team collaboration forum
  CONTRIBUTING.md
Labels: docs

#1951 Refactor moved message functionality from filter to message
  waku/filter.go
  waku/message.go
Labels: refactor

#1957 Refactor/waku tidy
  waku/api.go
  waku/api_test.go
  waku/common/envelope.go
  waku/common/filter_test.go
  waku/common/message.go
  waku/common/message_test.go
  waku/common/rate_limiter.go
  waku/v0/statusoptions_test.go
  waku/v0_test.go
  waku/waku.go
  waku/waku_test.go
  whisper/README.md
Labels: refactor
