Repository status-im/status-go, pull requests merged in 2022-05, with the labels that each got.

#2670 ci: pin builds to hosts with specific Go version
  _assets/ci/Jenkinsfile.android
  _assets/ci/Jenkinsfile.ios
  _assets/ci/Jenkinsfile.linux
  _assets/ci/Jenkinsfile.tests
Labels: jenkins

#2652 fix: delete account sync keystore
  account/accounts.go
  services/accounts/accounts.go
Labels: Tested: mobile

#2211 [WIP] Add user-facing explainer
  _docs/app-metrics.md
Labels: stale

#2663 feat: Add hasActivity param to derived addresses
  node/status_node_services.go
  services/accounts/accounts.go
  services/wallet/api.go
  services/wallet/service.go
Labels: Tested: mobile, Tested: desktop

#2607 Feat/wallet sync rebase
  api/backend.go
  api/backend_test.go
  api/geth_backend.go
  appdatabase/migrations/bindata.go
  appdatabase/migrations/sql/1652715604_add_clock_accounts.up.sql
  appdatabase/migrationsprevnodecfg/bindata.go
  cmd/ping-community/main.go
  cmd/populate-db/main.go
  mailserver/migrations/bindata.go
  mobile/status.go
  multiaccounts/accounts/account_test.go
  multiaccounts/accounts/database.go
  multiaccounts/accounts/database_test.go
  multiaccounts/migrations/bindata.go
  protocol/anonmetrics/migrations/migrations.go
  protocol/encryption/migrations/migrations.go
  protocol/encryption/protocol_message.pb.go
  protocol/messenger.go
  protocol/messenger_handler.go
  protocol/messenger_response.go
  protocol/messenger_sync_wallets_test.go
  protocol/migrations/migrations.go
  protocol/protobuf/anon_metrics.pb.go
  protocol/protobuf/application_metadata_message.pb.go
  protocol/protobuf/application_metadata_message.proto
  protocol/protobuf/chat_identity.pb.go
  protocol/protobuf/chat_message.pb.go
  protocol/protobuf/command.pb.go
  protocol/protobuf/communities.pb.go
  protocol/protobuf/contact.pb.go
  protocol/protobuf/emoji_reaction.pb.go
  protocol/protobuf/enums.pb.go
  protocol/protobuf/group_chat_invitation.pb.go
  protocol/protobuf/membership_update_message.pb.go
  protocol/protobuf/pairing.pb.go
  protocol/protobuf/pairing.proto
  protocol/protobuf/pin_message.pb.go
  protocol/protobuf/push_notifications.pb.go
  protocol/protobuf/status_update.pb.go
  protocol/protobuf/sync_settings.pb.go
  protocol/pushnotificationclient/migrations/migrations.go
  protocol/pushnotificationserver/migrations/migrations.go
  protocol/transport/migrations/migrations.go
  protocol/v1/status_message.go
  services/accounts/accounts.go
  services/stickers/api.go
  services/wallet/reader.go
  services/wallet/transfer/controller.go
  services/web3provider/api_test.go
  static/bindata.go
  t/bindata.go
Labels: Tested: mobile

#2664 fix: merge node config allows overide
  account/accounts_geth.go
  api/geth_backend.go
Labels: Tested: mobile

#2689 fix: get balance with multiple chain
  services/wallet/token.go
Labels: Tested: mobile, Tested: desktop
