Repository status-im/status-go, pull requests merged in 2022-09, with the labels that each got.

#2797 feat: Handle image in group chat
  VERSION
  images/encode.go
  protocol/anonmetrics/migrations/migrations.go
  protocol/chat.go
  protocol/encryption/migrations/migrations.go
  protocol/group_chat_system_messages.go
  protocol/messenger.go
  protocol/messenger_handler_test.go
  protocol/migrations/migrations.go
  protocol/migrations/sqlite/1660041928_add_chat_image.up.sql
  protocol/persistence.go
  protocol/protobuf/membership_update_message.pb.go
  protocol/protobuf/membership_update_message.proto
  protocol/pushnotificationclient/migrations/migrations.go
  protocol/pushnotificationserver/migrations/migrations.go
  protocol/transport/migrations/migrations.go
  protocol/v1/membership_update_message.go
  protocol/v1/membership_update_message_test.go
  services/chat/api.go
Labels: Tested: mobile

#2843 chore: change address of community portal testnet contract
  contracts/directory/address.go
Labels: Tested: desktop

#2810 chore: hardcode optimism testnet for retrieving communities portal
  contracts/contracts.go
  protocol/messenger_communities.go
Labels: Tested: mobile

#2850 fix: remove tenor.com from preview whitelist
  protocol/urls/urls.go
Labels: breaking change

#2796 feat: make kdf iterations configurable when creating a multiaccount
  VERSION
  api/geth_backend.go
  appdatabase/database.go
  appdatabase/database_test.go
  appdatabase/node_config_test.go
  appdatabase/test_helpers.go
  appmetrics/database_test.go
  cmd/ping-community/main.go
  cmd/populate-db/main.go
  cmd/statusd/main.go
  multiaccounts/database.go
  multiaccounts/database_test.go
  multiaccounts/migrations/bindata.go
  multiaccounts/migrations/sql/1660238799_accounts_kdf.up.sql
  multiaccounts/settings/database_test.go
  node/status_node_rpc_client_test.go
  protocol/common/message_sender_test.go
  protocol/communities/manager_test.go
  protocol/communities/persistence_test.go
  protocol/communities_messenger_test.go
  protocol/encryption/encryption_multi_device_test.go
  protocol/encryption/encryption_test.go
  protocol/encryption/multidevice/persistence_test.go
  protocol/encryption/persistence_keys_storage_test.go
  protocol/encryption/persistence_test.go
  protocol/encryption/protocol_test.go
  protocol/encryption/sharedsecret/service_test.go
  protocol/ens/persistence_test.go
  protocol/messenger.go
  protocol/messenger_config.go
  protocol/messenger_sync_settings_test.go
  protocol/messenger_test.go
  protocol/persistence_test.go
  protocol/pushnotificationclient/client_test.go
  protocol/pushnotificationclient/persistence_test.go
  protocol/pushnotificationserver/persistence_test.go
  protocol/pushnotificationserver/server_test.go
  protocol/sqlite/db.go
  protocol/sqlite/db_test.go
  protocol/transport/transport_test.go
  protocol/verification/persistence_test.go
  rpc/client_test.go
  rpc/network/network_test.go
  server/payload_manager_test.go
  services/appmetrics/api_test.go
  services/browsers/api_test.go
  services/ens/api_test.go
  services/gif/gif_test.go
  services/local-notifications/database_test.go
  services/mailservers/api_test.go
  services/permissions/api_test.go
  services/wakuext/api_test.go
  services/wallet/saved_addresses_test.go
  services/wallet/token_test.go
  services/wallet/transaction_test.go
  services/wallet/transfer/block_test.go
  services/wallet/transfer/database_test.go
  services/web3provider/api_test.go
  sqlite/sqlite.go
Labels: Tested: mobile
