Repository status-im/status-go, pull requests merged in 2022-08, with the labels that each got.

#2778 feat: add arbitrum tokens
  services/wallet/tokenstore.go
Labels: Tested: mobile, Tested: desktop

#2757 Timeout automatic status updates
  VERSION
  protocol/messenger.go
  protocol/messenger_communities.go
  protocol/messenger_config.go
  protocol/messenger_status_updates.go
  protocol/messenger_status_updates_test.go
  protocol/persistence.go
  services/ext/signal.go
  signal/events_messenger.go
Labels: Tested: mobile, Tested: desktop

#2781 feat: Update the asset traits to have the correct uppercase formats for trait values
  services/wallet/opensea.go
Labels: Tested: mobile, Tested: desktop

#2779 [#13647] Avoid rewriting of `response.Settings` on new acc sync
  VERSION
  protocol/messenger_handler.go
Labels: Tested: mobile, Tested: desktop

#2752 feat: introduce messenger APIs to extract discord channels
  appdatabase/migrations/bindata.go
  appdatabase/migrationsprevnodecfg/bindata.go
  mailserver/migrations/bindata.go
  multiaccounts/migrations/bindata.go
  protocol/anonmetrics/migrations/migrations.go
  protocol/communities_messenger_test.go
  protocol/discord/types.go
  protocol/encryption/migrations/migrations.go
  protocol/messenger_communities.go
  protocol/messenger_config.go
  protocol/messenger_response.go
  protocol/migrations/migrations.go
  protocol/protobuf/chat_message.pb.go
  protocol/protobuf/chat_message.proto
  protocol/pushnotificationclient/migrations/migrations.go
  protocol/pushnotificationserver/migrations/migrations.go
  protocol/transport/migrations/migrations.go
  services/ext/api.go
  services/ext/signal.go
  signal/events_discord_import.go
  static/bindata.go
  t/bindata.go
Labels: Tested: mobile, Tested: desktop

#2754 Feat/color in groupchat
  VERSION
  protocol/anonmetrics/migrations/migrations.go
  protocol/chat.go
  protocol/encryption/migrations/migrations.go
  protocol/encryption/protocol_message.pb.go
  protocol/group_chat_system_messages.go
  protocol/messenger.go
  protocol/messenger_handler_test.go
  protocol/migrations/migrations.go
  protocol/protobuf/anon_metrics.pb.go
  protocol/protobuf/chat_identity.pb.go
  protocol/protobuf/chat_message.pb.go
  protocol/protobuf/command.pb.go
  protocol/protobuf/communities.pb.go
  protocol/protobuf/contact.pb.go
  protocol/protobuf/contact_verification.pb.go
  protocol/protobuf/emoji_reaction.pb.go
  protocol/protobuf/enums.pb.go
  protocol/protobuf/group_chat_invitation.pb.go
  protocol/protobuf/membership_update_message.pb.go
  protocol/protobuf/membership_update_message.proto
  protocol/protobuf/pairing.pb.go
  protocol/protobuf/pin_message.pb.go
  protocol/protobuf/push_notifications.pb.go
  protocol/protobuf/status_update.pb.go
  protocol/protobuf/sync_settings.pb.go
  protocol/pushnotificationclient/migrations/migrations.go
  protocol/pushnotificationserver/migrations/migrations.go
  protocol/transport/migrations/migrations.go
  protocol/v1/membership_update_message.go
  protocol/v1/membership_update_message_test.go
  services/chat/api.go
Labels: Tested: mobile, Tested: desktop

#2776 feat: add optional inviteMessage to share-community request
  protocol/communities_messenger_test.go
  protocol/messenger_communities.go
  protocol/requests/share_community.go
Labels: Tested: mobile, desktop: tested-issues

#2756 fix: ens release username hash
  services/ens/api.go
  services/wallet/transaction.go
Labels: Tested: mobile, Tested: desktop

#2766 feat: introduce `discord_message_authors` persistence APIs
  appdatabase/migrations/bindata.go
  appdatabase/migrationsprevnodecfg/bindata.go
  mailserver/migrations/bindata.go
  multiaccounts/migrations/bindata.go
  protocol/anonmetrics/migrations/migrations.go
  protocol/encryption/migrations/migrations.go
  protocol/encryption/protocol_message.pb.go
  protocol/message_persistence.go
  protocol/migrations/migrations.go
  protocol/migrations/sqlite/1658236268_add_discord_message_authors_table.up.sql
  protocol/persistence_test.go
  protocol/protobuf/anon_metrics.pb.go
  protocol/protobuf/chat_identity.pb.go
  protocol/protobuf/chat_message.pb.go
  protocol/protobuf/command.pb.go
  protocol/protobuf/communities.pb.go
  protocol/protobuf/contact.pb.go
  protocol/protobuf/contact_verification.pb.go
  protocol/protobuf/emoji_reaction.pb.go
  protocol/protobuf/enums.pb.go
  protocol/protobuf/group_chat_invitation.pb.go
  protocol/protobuf/membership_update_message.pb.go
  protocol/protobuf/pairing.pb.go
  protocol/protobuf/pin_message.pb.go
  protocol/protobuf/push_notifications.pb.go
  protocol/protobuf/status_update.pb.go
  protocol/protobuf/sync_settings.pb.go
  protocol/pushnotificationclient/migrations/migrations.go
  protocol/pushnotificationserver/migrations/migrations.go
  protocol/transport/migrations/migrations.go
  static/bindata.go
  t/bindata.go
Labels: Tested: mobile

#2784 feat: add `discord_messages` table and persistence APIs
  protocol/common/message.go
  protocol/discord/types.go
  protocol/message_persistence.go
  protocol/migrations/migrations.go
  protocol/migrations/sqlite/1659619997_add_discord_messages_table.up.sql
  protocol/persistence_test.go
  protocol/protobuf/chat_message.pb.go
  protocol/protobuf/chat_message.proto
Labels: Tested: mobile

#2793 feat(CryptoCompareApi): Get token details from crypto compare
  services/wallet/api.go
  services/wallet/cryptocompare.go
  services/wallet/price.go
Labels: Tested: mobile, Tested: desktop

#2798 fix: Added support for initialization of CurrentUserStatus to Automatic after profile creation
  multiaccounts/settings/database.go
Labels: Tested: mobile, Tested: desktop

#2792 feat: obtain ENSUsername address from registry
  contracts/contracts.go
  contracts/registrar/address.go
  node/status_node_services.go
  services/ens/api.go
  services/ens/service.go
Labels: Tested: mobile, Tested: desktop

#2737 feat: log raw messages to csv for debugging
  params/config.go
  protocol/messenger.go
  protocol/messenger_config.go
  services/ext/service.go
Labels: Tested: mobile, Tested: desktop

#2789 [#13672] Sync contact request decision
  VERSION
  appdatabase/migrations/bindata.go
  appdatabase/migrationsprevnodecfg/bindata.go
  mailserver/migrations/bindata.go
  multiaccounts/migrations/bindata.go
  protocol/anonmetrics/migrations/migrations.go
  protocol/encryption/migrations/migrations.go
  protocol/messenger.go
  protocol/messenger_contacts.go
  protocol/messenger_handler.go
  protocol/migrations/migrations.go
  protocol/protobuf/application_metadata_message.pb.go
  protocol/protobuf/application_metadata_message.proto
  protocol/protobuf/pairing.pb.go
  protocol/protobuf/pairing.proto
  protocol/pushnotificationclient/migrations/migrations.go
  protocol/pushnotificationserver/migrations/migrations.go
  protocol/transport/migrations/migrations.go
  protocol/v1/status_message.go
  static/bindata.go
  t/bindata.go
Labels: Tested: mobile

#2795 change ipfs gateway and add Mode build param
  Makefile
  VERSION
  api/geth_backend.go
  ipfs/ipfs.go
  params/version.go
  services/ens/api.go
  services/ens/api_test.go
  services/stickers/api.go
Labels: Tested: desktop
