Repository status-im/status-go, pull requests merged in 2023-11, with the labels that each got.

#4281 fix: edit message even if converting link previews to proto
  protocol/messenger.go
  protocol/messenger_messages.go
Labels: E:New Unfurling API

#4283 fix: correct parsing shared url without data
  protocol/communities/community.go
  protocol/linkpreview_unfurler_status.go
  protocol/messenger_share_urls.go
  protocol/messenger_share_urls_test.go
  protocol/requests/community_channel_share_url.go
  services/ext/api.go
Labels: E:Desktop New Share URL Format

#4312 fix: self-contact related flaky tests
  protocol/messenger.go
  protocol/messenger_contacts.go
  protocol/messenger_contacts_test.go
  protocol/messenger_identity.go
  protocol/messenger_linkpreview_test.go
  protocol/messenger_sync_settings.go
  protocol/messenger_testing_utils.go
Labels: E:Flaky Test

#4344 makefile: fix linking Git hooks on MacOS
  Makefile
Labels: infra

#4365 Resend community offline updates
  protocol/communities_messenger_helpers_test.go
  protocol/messenger.go
  protocol/messenger_config.go
  protocol/messenger_offline_test.go
  protocol/messenger_test.go
  protocol/migrations/migrations.go
  protocol/migrations/sqlite/1700820989_add_resend_automatically_index.up.sql
  protocol/persistence.go
  protocol/persistence_test.go
  wakuv2/waku.go
Labels: release blocker
