Repository status-im/status-go, pull requests merged in 2023-04, with the labels that each got.

#3368 Fixed local pairing Server connection events firing early
  server/pairing/handlers.go
Labels: local-pairing

#3377 ci: use Nix shell for Linux library builds
  _assets/ci/Jenkinsfile
  _assets/ci/Jenkinsfile.android
  _assets/ci/Jenkinsfile.docker
  _assets/ci/Jenkinsfile.ios
  _assets/ci/Jenkinsfile.linux
  _assets/ci/Jenkinsfile.tests
Labels: devops

#3438 ci: upgrade Xcode version required to 14.3
  _assets/ci/Jenkinsfile.ios
  shell.nix
Labels: infra
