Repository status-im/status-go, pull requests merged in 2024-08, with the labels that each got.

#5559 chore: lightmode ping peers when we come back online,
  go.mod
  go.sum
  vendor/github.com/waku-org/go-waku/waku/v2/api/filter.go
  vendor/github.com/waku-org/go-waku/waku/v2/node/localnode.go
  vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go
  vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_discovery.go
  vendor/github.com/waku-org/go-waku/waku/v2/peermanager/peer_manager.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/filter/client.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/filter/filter_health_check.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/filter/server.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/legacy_store/waku_store_client.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/lightpush/waku_lightpush.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/metadata/waku_metadata.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange/client.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange/protocol.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/store/client.go
  vendor/modules.txt
  wakuv2/filter_manager.go
  wakuv2/waku.go
  wakuv2/waku_test.go
Labels: E:Mobile release 2.30

#5705 Added User Agent to rpc client configuration
  rpc/client.go
  rpc/client_test.go
Labels: proxy-server

#5721 Added application version to the RPC user client
  rpc/client.go
  rpc/client_test.go
Labels: proxy-server

#5747 chore(ci)_: fix formatting, bump library version
  _assets/ci/Jenkinsfile
  _assets/ci/Jenkinsfile.android
  _assets/ci/Jenkinsfile.docker
  _assets/ci/Jenkinsfile.ios
  _assets/ci/Jenkinsfile.linux
  _assets/ci/Jenkinsfile.tests
  _assets/ci/Jenkinsfile.tests-rpc
  _assets/ci/validate-vendor.sh
Labels: infra

#5773 fix_: separate commit message check
  .github/workflows/commit-check.yml
  Makefile
  _assets/ci/Jenkinsfile.tests
  _assets/scripts/commit_check.sh
Labels: infra
