Repository status-im/status-go, pull requests merged in 2024-11, with the labels that each got.

#6045 chore_: cleanup unused cmd
  .gitignore
  .travis.yml
  BOOTNODE.md
  CMakeLists.txt
  MAILSERVER.md
  Makefile
  README.md
  WAKU.md
  _assets/build/Dockerfile-bootnode
  _assets/build/Dockerfile-prune
  _assets/ci/Jenkinsfile.tests
  _assets/compose/bootnode/Makefile
  _assets/compose/bootnode/README.md
  _assets/compose/bootnode/docker-compose.yml
  _assets/compose/mailserver/Makefile
  _assets/compose/mailserver/README.md
  _assets/compose/mailserver/docker-compose.yml
  _assets/compose/metrics-collector/config.grafana.env
  _assets/compose/metrics-collector/docker-compose.yml
  _assets/compose/metrics-collector/prometheus/prometheus.yml
  _assets/compose/wnode-test-cluster/README.md
  _assets/compose/wnode-test-cluster/docker-compose.yml
  _assets/compose/wnode-test-cluster/wnode-config.json
  _assets/scripts/canary_test_mailservers.sh
  _assets/systemd/bootnode/Makefile
  _assets/systemd/bootnode/README.md
  _assets/systemd/bootnode/service.template
  _docs/how-to-build.md
  _examples/README.md
  _examples/waku.json
  _examples/wakuv2.json
  _examples/whisper.json
  api/backend.go
  cmd/bootnode/README.md
  cmd/bootnode/main.go
  cmd/node-canary/README.md
  cmd/node-canary/main.go
  cmd/spiff-workflow/.gitignore
  cmd/spiff-workflow/README.md
  cmd/spiff-workflow/flags.go
  cmd/spiff-workflow/main.go
  cmd/spiff-workflow/signing_phrase.go
  cmd/topics/main.go
  static/keys/bootnode.key
Labels: breaking change

#6061 test_: updated profile tests
  tests-functional/tests/test_wakuext_profile.py
Labels: E:Tests

#6054 feat_: add Sentry panic reporting
  .gitignore
  api/geth_backend.go
  cmd/status-backend/main.go
  common/utils.go
  internal/sentry/README.md
  internal/sentry/options.go
  internal/sentry/options_test.go
  internal/sentry/params.go
  internal/sentry/params_test.go
  internal/sentry/sentry.go
  internal/sentry/sentry_test.go
  internal/sentry/stacktrace.go
  internal/sentry/stacktrace_test.go
  mobile/callog/status_request_log.go
  mobile/status.go
  protocol/requests/initialize_application.go
Labels: do not merge

#5857 feat!: extract storenode cycle to go-waku api
  eth-node/bridge/geth/waku.go
  eth-node/bridge/geth/wakuv2.go
  eth-node/types/mailserver.go
  eth-node/types/topic.go
  eth-node/types/waku.go
  go.mod
  go.sum
  protocol/messenger.go
  protocol/messenger_communities.go
  protocol/messenger_contacts.go
  protocol/messenger_mailserver.go
  protocol/messenger_mailserver_cycle.go
  protocol/messenger_mailserver_processMailserverBatch_test.go
  protocol/messenger_store_node_request_manager.go
  protocol/messenger_store_node_request_manager_config.go
  protocol/messenger_storenode_comunity_test.go
  protocol/messenger_storenode_request_test.go
  protocol/messenger_testing_utils.go
  protocol/storenodes/storenodes.go
  protocol/transport/transport.go
  services/ext/api.go
  vendor/github.com/waku-org/go-waku/logging/logging.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/common/result.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/history/cycle.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/history/emitters.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/history/history.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/history/sort.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/missing/default_requestor.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/missing/missing_messages.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/publish/default_publisher.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/publish/default_verifier.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/publish/message_check.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/publish/message_sender.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/store/client.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/store/options.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/store/result.go
  vendor/modules.txt
  wakuv2/history_processor_wrapper.go
  wakuv2/waku.go
  wakuv2/waku_test.go
Labels: breaking change

#6102 feat!: implement new activityV2 filter
  services/wallet/activity/activity.go
  services/wallet/activity/activity_v2.go
  services/wallet/activity/errors.go
  services/wallet/activity/filter.go
  services/wallet/activity/service.go
  services/wallet/activity/service_test.go
  services/wallet/activity/session.go
  services/wallet/activity/session_service.go
  services/wallet/activity/session_service_test.go
  services/wallet/api.go
  services/wallet/routeexecution/manager.go
  services/wallet/service.go
  services/wallet/transfer/transaction_manager_route.go
  tests-functional/clients/signals.py
  tests-functional/tests/test_wallet_activity_session.py
  tests-functional/wallet_utils.py
  transactions/testhelpers.go
  walletdatabase/migrations/sql/1730807123_add_from_to_address_virtual_columns_to_route_input_data.up.sql
Labels: breaking change

#6106 perf!: Optimize Filter Initialization with Concurrent Processing
  protocol/communities/manager.go
  protocol/messenger.go
  protocol/messenger_chats.go
  protocol/messenger_filter_init.go
  services/ext/api.go
Labels: breaking change
