Repository status-im/status-go, pull requests merged in 2024-10, with the labels that each got.

#5884 fix(communities)!: stop syncing community on `LastOpenedAt` update
  protocol/communities_messenger_test.go
  protocol/messenger_communities.go
Labels: breaking change

#5920 fix(make)_: avoid calling version script unnecessarily
  Makefile
Labels: infra, nix

#5955 docs_: better usage docs for status-backend
  README.md
  cmd/status-backend/README.md
Labels: goal:P2:increase-functionsal-tests-coverage

#5956 chore_: configure tests develop job
  _assets/ci/Jenkinsfile.tests
Labels: goal:P1:increase-coverage-tx-pkgs, goal:P2:increase-tests-coverage, goal:P2:increase-functionsal-tests-coverage

#6009 fix_: create request logger ad-hoc in tests
  logutils/requestlog/request_log.go
  mobile/callog/status_request_log.go
  mobile/callog/status_request_log_test.go
  mobile/init_logging_test.go
  mobile/status.go
  mobile/status_test.go
Labels: goal:status-go:P1:no-flaky-tests, goal:status-go:P2:no-annoying-ci-checks
