Repository status-im/status-go, pull requests merged in 2024-12, with the labels that each got.

#6160 fix!: add forceRefresh parameter to FetchOrGetCachedWalletBalances endpoint
  protocol/messenger_wallet.go
  services/wallet/api.go
  services/wallet/api_test.go
  services/wallet/reader.go
Labels: breaking change

#6150 feat_: api logging signals
  mobile/callog/status_request_log.go
  mobile/callog/status_request_log_test.go
  mobile/status.go
  signal/signals.go
Labels: goal:status-go:P1:no-leaks-in-logs

#6189 feat_: graceful shutdown with status-backend
  cmd/status-backend/main.go
Labels: cmd, functional tests

#6190 feat_: SensitiveString type
  internal/security/sensitive_string.go
  internal/security/sensitive_string_test.go
Labels: goal:status-go:P0:no-critical-leaks, goal:status-go:P1:no-leaks-in-logs

#6194 fix_: remove logging of rpc endpoint
  protocol/ens/verifier.go
Labels: goal:status-go:P0:no-critical-leaks

#6193 fix_: remove logging of rpc endpoint
  protocol/ens/verifier.go
Labels: goal:status-go:P0:no-critical-leaks

#6205 test_: skip flaky `TestService_IncrementalUpdateMixed`
  services/wallet/activity/session_service_test.go
Labels: E:Flaky Test, goal:status-go:P2:no-annoying-ci-checks

#6217 fix_: add `infuraSecret` and `statusProxyBlockchainPassword` to secrets
  mobile/callog/status_request_log.go
Labels: goal:status-go:P0:no-critical-leaks, goal:status-go:P1:no-leaks-in-logs

#6201 feat_: status-backend health endpoint
  cmd/status-backend/README.md
  cmd/status-backend/server/api/health.go
  cmd/status-backend/server/server.go
  tests-functional/README.MD
  tests-functional/clients/status_backend.py
  tests-functional/tests/test_init_status_app.py
Labels: functional tests

#6172 chore(block)!: remove desktop BlockContact function for parity
  protocol/messenger_contacts.go
  services/ext/api.go
Labels: breaking change
