Repository status-im/status-go, pull requests merged in 2024-07, with the labels that each got.

#5440 feat: aggregate filter subscriptions to do bulk subs with peer
  go.mod
  go.sum
  protocol/messenger_communities.go
  protocol/messenger_communities_sharding_test.go
  vendor/github.com/waku-org/go-waku/waku/v2/api/filter.go
  vendor/github.com/waku-org/go-waku/waku/v2/node/localnode.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/enr/enr.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/subscription/subscription_details.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/subscription/subscriptions_map.go
  vendor/modules.txt
  wakuv2/filter_manager.go
  wakuv2/waku_test.go
Labels: E:Mobile release 2.30

#5366 chore_: limit max number of ephemeral keys to 3
  protocol/common/message_sender.go
  protocol/common/message_sender_test.go
  protocol/pushnotificationclient/client.go
Labels: E:Mobile release 2.30

#5506 feat(wallet)!: return routerV2 suggested routes whenever available, o…
  services/wallet/router/router_v2.go
  services/wallet/router/router_v2_test.go
  services/wallet/router/router_v2_test_data.go
Labels: swap-team

#5519 fix: lightclient enr shards
  go.mod
  go.sum
  vendor/github.com/waku-org/go-waku/waku/v2/node/localnode.go
  vendor/github.com/waku-org/go-waku/waku/v2/node/wakunode2.go
  vendor/github.com/waku-org/go-waku/waku/v2/node/wakuoptions.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/lightpush/waku_lightpush.go
  vendor/modules.txt
  wakuv2/waku.go
Labels: E:Mobile release 2.30

#5474 refactor: only use shards
  api/defaults.go
  api/messenger_raw_message_resend_test.go
  cmd/ping-community/main.go
  config/cli/fleet-shards.test.json
  go.mod
  go.sum
  node/status_node_services.go
  nodecfg/node_config.go
  params/config.go
  protocol/common/shard/shard.go
  protocol/communities/manager.go
  protocol/communities_messenger_helpers_test.go
  protocol/communities_messenger_shared_member_address_test.go
  protocol/communities_messenger_test.go
  protocol/communities_messenger_token_permissions_test.go
  protocol/messenger.go
  protocol/messenger_communities.go
  protocol/messenger_communities_sharding_test.go
  protocol/messenger_handler.go
  protocol/messenger_messages_tracking_test.go
  protocol/messenger_offline_test.go
  protocol/messenger_storenode_comunity_test.go
  protocol/messenger_storenode_request_test.go
  protocol/transport/filters_manager.go
  protocol/transport/transport.go
  protocol/waku_builder_test.go
  telemetry/client_test.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/filter/client.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/lightpush/waku_lightpush.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/lightpush/waku_lightpush_option.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/metadata/waku_metadata.go
  vendor/github.com/waku-org/go-waku/waku/v2/protocol/subscription/subscriptions_map.go
  vendor/modules.txt
  wakuv2/api_test.go
  wakuv2/config.go
  wakuv2/waku.go
  wakuv2/waku_test.go
Labels: E:Mobile release 2.30

#5542 feat(wallet)_: incorporate partner fees for L1 paraswap swaps
  services/wallet/common/const.go
  services/wallet/router/pathprocessor/processor_swap_paraswap.go
  services/wallet/router/pathprocessor/processor_swap_paraswap_test.go
  services/wallet/thirdparty/paraswap/client_v5.go
  services/wallet/thirdparty/paraswap/request_build_transaction.go
  services/wallet/thirdparty/paraswap/request_price_route.go
Labels: swap-team, E:Swap Backend M1

#5576 fix_: return array of account without accounts key
  services/connector/commands/accounts.go
  services/connector/commands/accounts_test.go
  services/connector/commands/request_accounts_test.go
  services/connector/connector_flows_test.go
Labels: backend-team

#5566 feat_:implement connector requestPermissions api
  services/connector/api.go
  services/connector/commands/request_permissions.go
  services/connector/commands/request_permissions_test.go
Labels: backend-team

#5584 fix_: return default chainID instead of throwing error for unregistered dApps
  services/connector/api.go
  services/connector/chainutils/utils.go
  services/connector/commands/chain_id.go
  services/connector/commands/chain_id_test.go
  services/connector/commands/switch_ethereum_chain.go
Labels: backend-team

#5600 fix_: conversion from int to string causes code scanning error
  services/wallet/common/const.go
Labels: backend-team

#5570 fix_: add missing message verification flag when creating an account
  api/defaults.go
  protocol/requests/create_account.go
Labels: E:Mobile release 2.30

#5598 fix_: return default chainID instead of throwing error for unregister…
  services/connector/api.go
  services/connector/chainutils/utils.go
  services/connector/commands/chain_id.go
  services/connector/commands/chain_id_test.go
  services/connector/commands/switch_ethereum_chain.go
Labels: backend-team
